# Generated by Django 6.0.4 on 2026-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.URLField(blank=True, null=True),
        ),
    ]
